"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { useSearchParams } from "next/navigation";
import PageHeader from "../../../components/PageHeader";
import { api } from "../../../lib/api";
import { useRealtimeRefresh } from "../../../lib/realtime/client";
import { EmptyState, Icon, Skeleton, Toast, ConfirmDialog } from "../../../components/ui/UI";

const types=["","message","email","call","media","alarm","reminder","event","system","progress","service","other"];
function relativeDate(value:string){const d=new Date(value);const now=new Date();if(d.toDateString()===now.toDateString())return d.toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"});return d.toLocaleDateString([], {month:"short",day:"numeric"})}

export default function NotificationsPage(){
  const params=useSearchParams();
  const [items,setItems]=useState<any[]>([]);const [devices,setDevices]=useState<any[]>([]);const [search,setSearch]=useState("");const [query,setQuery]=useState("");const [unread,setUnread]=useState(false);const [deviceId,setDeviceId]=useState("");const [type,setType]=useState("");const [nextCursor,setNextCursor]=useState<string|null>(null);const [selected,setSelected]=useState<any>(null);const [loading,setLoading]=useState(true);const [loadingMore,setLoadingMore]=useState(false);const [error,setError]=useState("");const [toast,setToast]=useState<{message:string;tone:"success"|"error"|"info"}|null>(null);const [checked,setChecked]=useState<Set<string>>(new Set());const [confirm,setConfirm]=useState<"delete-one"|"delete-selected"|null>(null);const [busy,setBusy]=useState(false);
  const load=useCallback(async(next?:string|null)=>{const isMore=Boolean(next);isMore?setLoadingMore(true):setLoading(true);setError("");try{const qs=new URLSearchParams({limit:"50"});if(query)qs.set("search",query);if(unread)qs.set("unread","1");if(deviceId)qs.set("deviceId",deviceId);if(type)qs.set("type",type);if(next)qs.set("cursor",next);const r=await api(`/notifications?${qs.toString()}`);setItems(prev=>isMore?[...prev,...(r.items||[])]:r.items||[]);setNextCursor(r.nextCursor||null);if(!isMore&&selected){const fresh=(r.items||[]).find((x:any)=>x.id===selected.id);if(fresh)setSelected(fresh)}}catch(e:any){setError(e.message||"Could not load notifications.")}finally{isMore?setLoadingMore(false):setLoading(false)}},[query,unread,deviceId,type,selected]);
  useEffect(()=>{api("/devices").then(r=>setDevices(r.devices||[])).catch(()=>{})},[]);
  useEffect(()=>{load()},[query,unread,deviceId,type]);
  useEffect(()=>{const id=params.get("selected");if(!id)return;const hit=items.find(n=>String(n.id)===id);if(hit){setSelected(hit);return}let active=true;api(`/notifications/${encodeURIComponent(id)}`).then(r=>{if(active&&r.notification)setSelected(r.notification)}).catch(()=>{});return()=>{active=false}},[params,items]);
  useRealtimeRefresh(["notification","notification.read","notification.unread","notifications.read-all","notifications.bulk-read","notification.deleted","notifications.bulk-deleted"], load);
  async function markRead(id:string){try{const r=await api(`/notifications/${id}/read`,{method:"POST"});setItems(v=>v.map(n=>n.id===id?{...n,read_at:r.readAt}:n));setSelected((s:any)=>s?.id===id?{...s,read_at:r.readAt}:s)}catch(e:any){setToast({message:e.message||"Could not update notification.",tone:"error"})}}
  async function toggle(id:string,read:boolean){try{await api(`/notifications/${id}/${read?"unread":"read"}`,{method:"POST"});const at=read?null:new Date().toISOString();setItems(v=>v.map(n=>n.id===id?{...n,read_at:at}:n));setSelected((s:any)=>s?.id===id?{...s,read_at:at}:s)}catch(e:any){setToast({message:e.message||"Could not update notification.",tone:"error"})}}
  async function confirmDelete(){setBusy(true);try{if(confirm==="delete-one"&&selected){await api(`/notifications/${selected.id}`,{method:"DELETE"});setItems(v=>v.filter(n=>n.id!==selected.id));setSelected(null);setToast({message:"Notification deleted.",tone:"success"})}if(confirm==="delete-selected"){const ids=[...checked];if(ids.length){await api("/notifications/bulk-delete",{method:"POST",body:JSON.stringify({ids})});setItems(v=>v.filter(n=>!checked.has(n.id)));setChecked(new Set());setSelected((s:any)=>s&&checked.has(s.id)?null:s);setToast({message:`${ids.length} notification${ids.length===1?"":"s"} deleted.`,tone:"success"})}}}catch(e:any){setToast({message:e.message||"Could not delete notifications.",tone:"error"})}finally{setBusy(false);setConfirm(null)}}
  async function bulkRead(){const ids=[...checked];if(!ids.length)return;try{await api("/notifications/bulk-read",{method:"POST",body:JSON.stringify({ids})});setItems(v=>v.map(n=>checked.has(n.id)?{...n,read_at:new Date().toISOString()}:n));setChecked(new Set());setToast({message:`${ids.length} marked as read.`,tone:"success"})}catch(e:any){setToast({message:e.message||"Could not update notifications.",tone:"error"})}}
  async function allRead(){try{await api("/notifications/read-all",{method:"POST"});setItems(v=>v.map(n=>({...n,read_at:n.read_at||new Date().toISOString()})));setToast({message:"Inbox marked as read.",tone:"success"})}catch(e:any){setToast({message:e.message||"Could not update inbox.",tone:"error"})}}
  const allChecked=items.length>0&&items.every(n=>checked.has(n.id));const selectedCount=checked.size;const selectedId=selected?.id;const selectedMeta=useMemo(()=>selected?[["Device",selected.device_name],["Received",new Date(selected.received_at).toLocaleString()],["Type",selected.notification_type||"Other"],["Package",selected.package_name||"—"]]:[],[selected]);
  return <>
    <PageHeader eyebrow="Inbox" title="Notifications" description="Review the notifications shared from your paired child devices." actions={<button className="btn ghost" onClick={allRead} disabled={!items.length}><Icon name="checkCircle" size={16}/> Mark all read</button>}/>
    <section className="card toolbar" aria-label="Notification filters"><div className="grow" style={{position:"relative"}}><Icon name="search" size={16}/><input className="input" style={{paddingLeft:38}} value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")setQuery(search.trim())}} placeholder="Search apps, devices or packages" aria-label="Search notifications"/></div><select className="input filterSelect" value={deviceId} onChange={e=>setDeviceId(e.target.value)} aria-label="Filter by device"><option value="">All devices</option>{devices.map(d=><option value={d.id} key={d.id}>{d.name}</option>)}</select><select className="input filterSelect" value={type} onChange={e=>setType(e.target.value)} aria-label="Filter by type">{types.map(t=><option value={t} key={t}>{t?t[0].toUpperCase()+t.slice(1):"All types"}</option>)}</select><button className={`filterChip ${unread?"active":""}`} onClick={()=>setUnread(v=>!v)}><Icon name="eye" size={15}/> Unread only</button><button className="btn primary" onClick={()=>setQuery(search.trim())}><Icon name="search" size={15}/> Search</button></section>
    {error&&<div className="error" style={{marginTop:13}}>{error} <button className="linkText" style={{border:0,background:"transparent",padding:0}} onClick={()=>load()}>Retry</button></div>}
    {selectedCount>0&&<div className="selectionBar" style={{marginTop:13}}><span><b>{selectedCount}</b> selected</span><div className="row"><button className="btn ghost" onClick={bulkRead}><Icon name="check" size={15}/> Mark read</button><button className="btn danger" onClick={()=>setConfirm("delete-selected")}><Icon name="trash" size={15}/> Delete</button><button className="iconButton" onClick={()=>setChecked(new Set())} aria-label="Clear selection"><Icon name="x"/></button></div></div>}
    <div className="inboxLayout"><section className="card inboxList" aria-label="Notification list"><div className="selectionBar" style={{justifyContent:"flex-start",gap:10}}><input className="checkBox" type="checkbox" checked={allChecked} onChange={e=>setChecked(e.target.checked?new Set(items.map(n=>n.id)):new Set())} aria-label="Select all visible notifications"/><span>{loading?"Loading…":`${items.length}${nextCursor?"+":""} notifications`}</span></div>{loading?<>{Array.from({length:8}).map((_,i)=><div className="inboxRow" key={i}><Skeleton className="box"/><div className="itemMain"><Skeleton className="title"/><div style={{height:7}}/><Skeleton className="text"/></div></div>)}</>:items.length?items.map(n=><div key={n.id} className={`inboxRow ${selectedId===n.id?"selected":""}`}><input className="checkBox" type="checkbox" checked={checked.has(n.id)} onChange={e=>setChecked(v=>{const next=new Set(v);e.target.checked?next.add(n.id):next.delete(n.id);return next})} aria-label={`Select notification from ${n.app_name||"app"}`}/><button onClick={()=>{setSelected(n);if(!n.read_at)markRead(n.id)}} style={{border:0,background:"transparent",padding:0,textAlign:"left",flex:1,minWidth:0,color:"inherit"}}><div className="itemMain"><h3><span className="appIcon" style={{width:34,height:34,borderRadius:10,fontSize:12,display:"inline-grid",verticalAlign:"middle",marginRight:9}}>{String(n.app_name||"?").slice(0,1).toUpperCase()}</span>{n.app_name||"Unknown app"}{!n.read_at&&<span className="badge green">New</span>}</h3><p>{n.content_state==="withheld"?"Message content sharing is off.":(n.title||"Notification content unavailable")}</p><div className="inboxMeta">{n.device_name||"Child device"} · {relativeDate(n.received_at)}</div></div></button><button className="iconButton" onClick={()=>toggle(n.id,Boolean(n.read_at))} aria-label={n.read_at?"Mark notification unread":"Mark notification read"}><Icon name={n.read_at?"eye":"check"} size={16}/></button></div>):<EmptyState icon="bell" title="Nothing here yet" body={query||unread||deviceId||type?"Try a broader search or clear a filter.":"Shared notifications will appear here when the child device starts sending them."} action={(query||unread||deviceId||type)?<button className="btn ghost" onClick={()=>{setSearch("");setQuery("");setUnread(false);setDeviceId("");setType("")}}>Clear filters</button>:undefined}/>} {nextCursor&&<div className="loadMore"><button className="btn ghost" onClick={()=>load(nextCursor)} disabled={loadingMore}>{loadingMore?"Loading more…":"Load older notifications"}</button></div>}</section>
      <aside className={`card detailCard ${selected?"mobileVisible":""}`} aria-label="Notification details">{selected?<><div className="detailTop"><div style={{minWidth:0}}><div className="eyebrow">Notification detail</div><h2>{selected.app_name||"Unknown app"}</h2><div className="small muted">{selected.device_name||"Child device"} · {new Date(selected.received_at).toLocaleString()}</div></div><button className="iconButton" onClick={()=>setSelected(null)} aria-label="Close notification details"><Icon name="x"/></button></div><div className="row" style={{marginTop:13,flexWrap:"wrap"}}>{selected.notification_type&&<span className="badge">{selected.notification_type}</span>}{selected.content_state&&<span className="badge">{selected.content_state}</span>}{selected.read_at?<span className="badge">Read</span>:<span className="badge green">Unread</span>}</div><div className="detailTitle"><strong>{selected.title||"No title available"}</strong><div style={{marginTop:10}} className="detailBody">{selected.content_state==="withheld"?"Message content sharing is currently turned off on the child device.":(selected.body||"Android did not expose readable message content for this notification.")}</div></div><div className="detailMeta">{selectedMeta.map(([label,value])=><div className="metaBox" key={label}><span>{label}</span><b>{value}</b></div>)}</div><div className="row" style={{marginTop:18,justifyContent:"flex-end",flexWrap:"wrap"}}><button className="btn ghost" onClick={()=>toggle(selected.id,!selected.read_at)}><Icon name={selected.read_at?"eye":"check"}/>{selected.read_at?"Mark unread":"Mark read"}</button><button className="btn danger" onClick={()=>setConfirm("delete-one")}><Icon name="trash"/> Delete</button></div></>:<div style={{height:"100%",minHeight:430,display:"grid",placeItems:"center",textAlign:"center"}}><div><div className="emptyIcon"><Icon name="bell"/></div><h3>Select a notification</h3><p className="small muted">Choose an item from your inbox to see its full details.</p></div></div>}</aside>
    </div>
    {toast&&<Toast {...toast} onClose={()=>setToast(null)}/>}<ConfirmDialog open={Boolean(confirm)} title={confirm==="delete-one"?"Delete this notification?":"Delete selected notifications?"} body={confirm==="delete-one"?"This removes the notification from your parent account. The original notification remains on the child device if it is still there.":`This permanently removes ${selectedCount} notification${selectedCount===1?"":"s"} from your parent account.`} confirmLabel="Delete" danger busy={busy} onCancel={()=>setConfirm(null)} onConfirm={confirmDelete}/>
  </>;
}
